// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuBGMrc_UtmNzDxNM39t7HUbSRBqwrmg',
    appId: '1:1052984801220:android:1c3ac5f49bb9ef55665691',
    messagingSenderId: '1052984801220',
    projectId: 'preticor-b8c0d',
    storageBucket: 'preticor-b8c0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8r1gOO58amKDoEvMHFWRse7pxHkUzeM8',
    appId: '1:1052984801220:ios:bc7f5fe928133d92665691',
    messagingSenderId: '1052984801220',
    projectId: 'preticor-b8c0d',
    storageBucket: 'preticor-b8c0d.appspot.com',
    androidClientId: '1052984801220-e8oflf2ih936n6hptbn5b401i6ickttq.apps.googleusercontent.com',
    iosClientId: '1052984801220-bput4neguhinlti2rbejm9bv6kpdrkn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumvida',
  );
}
